name: brick_rest_generators
description: Code generation library for the REST providers, models, and adapters in Brick
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_rest_generators
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 4.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ^8.0.0
  brick_build:
    path: ../brick_build
  brick_core:
    path: ../brick_core
  brick_json_generators:
    path: ../brick_json_generators
  brick_rest:
    path: ../brick_rest
  build: ">=3.0.0 <5.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  source_gen: ">=3.0.0 <5.0.0"

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  lints:
  test:
