name: brick_offline_first_with_supabase
description: A Brick domain that routes data fetching through local providers
  before a Supabase provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_supabase
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 2.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_core:
    path: ../brick_core
  brick_offline_first:
    path: ../brick_offline_first
  brick_offline_first_with_rest:
    path: ../brick_offline_first_with_rest
  brick_sqlite:
    path: ../brick_sqlite
  brick_supabase:
    path: ../brick_supabase
  http: ">=1.0.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  sqflite_common: ">=2.5.0 <3.0.0"
  supabase: ">=2.3.0 <3.0.0"

dev_dependencies:
  lints:
  mockito:
  sqflite_common_ffi:
  test:
