name: brick_offline_first_with_graphql
description: A Brick domain that routes data fetching through local providers
  before a GraphQL provider.
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_graphql
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 4.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  brick_core:
    path: ../brick_core
  brick_graphql:
    path: ../brick_graphql
  brick_offline_first:
    path: ../brick_offline_first
  brick_sqlite:
    path: ../brick_sqlite
  gql: ">=0.13.0 <2.0.0"
  gql_exec: ">=0.3.0 <2.0.0"
  gql_link: ">=0.4.0 <2.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  sqflite_common: ">=2.5.0 <3.0.0"

dev_dependencies:
  lints:
  mockito:
  sqflite_common_ffi:
  test:
