name: brick_offline_first_with_supabase_build
description: Code generation library for the Brick Offline First Domain using Supabase
homepage: https://github.com/GetDutchie/brick/tree/main/packages/brick_offline_first_with_supabase_build
issue_tracker: https://github.com/GetDutchie/brick/issues
repository: https://github.com/GetDutchie/brick

version: 2.0.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  analyzer: ">=6.11.0 <8.0.0"
  brick_build:
    path: ../brick_build
  brick_offline_first:
    path: ../brick_offline_first
  brick_offline_first_build:
    path: ../brick_offline_first_build
  brick_offline_first_with_supabase:
    path: ../brick_offline_first_with_supabase
  brick_sqlite:
    path: ../brick_sqlite
  brick_sqlite_generators:
    path: ../brick_sqlite_generators
  brick_supabase:
    path: ../brick_supabase
  brick_supabase_generators:
    path: ../brick_supabase_generators
  build: ">=3.0.0 <5.0.0"
  dart_style: ">=3.0.0 <4.0.0"
  logging: ">=1.0.0 <2.0.0"
  meta: ">=1.3.0 <2.0.0"
  path: ">=1.9.0 <2.0.0"
  source_gen: ">=3.0.0 <5.0.0"

dev_dependencies:
  brick_build_test:
    path: ../brick_build_test
  build_verify:
  lints:
  source_gen_test:
  test:
